name: DOCKERHUB Get
description: Get DOCKERHUB environment variables
author: a3.services
branding:
  icon: settings
  color: purple
inputs:
  summary:
    description: 'Enable or disable the summary output'
    required: false
    default: 'false'
outputs: {}
runs:
  using: composite
  steps:
    - name: Download environment variables
      uses: actions/download-artifact@v4
      with:
        name: dockerhub-env
    
    - name: Set DOCKERHUB environment variables
      shell: sh
      run: |
        cat dockerhub.env >> ${GITHUB_ENV}
      
    - name: Summary
      shell: sh
      if: ${{ inputs.summary == 'true' }}
      run: |
        echo "### DOCKERHUB Environment Variables" >> $GITHUB_STEP_SUMMARY
        echo "| Variable           | Value              |" >> $GITHUB_STEP_SUMMARY
        echo "|--------------------|--------------------|" >> $GITHUB_STEP_SUMMARY
        while IFS='=' read -r key value; do
          if [ "$key" = "DOCKERHUB_TOKEN" ]; then
            length=${#value}
            if [ "$length" -gt 10 ]; then
              start=$(echo "$value" | cut -c 1-5)
              end=$(echo "$value" | cut -c $((length-4))-$length)
              
              # Vypočíta počet skrytých znakov a vygeneruje presný počet hviezdičiek
              hidden_len=$((length - 10))
              stars=$(printf "%${hidden_len}s" | tr ' ' '*')
              
              value="${start}${stars}${end}"
            fi
          fi
          echo "| $key | $value |" >> $GITHUB_STEP_SUMMARY
        done < dockerhub.env
